import PDFDocument from "pdfkit";
import Meeting from "../models/Meeting.js";
import Task from "../models/Task.js";

export const generateReport = async (req, res) => {
  try {
    const { id } = req.params;

    // =========================
    // GET MEETING
    // =========================
    const meeting = await Meeting.findById(id);

    if (!meeting) {
      return res.status(404).json({
        message: "Meeting not found",
      });
    }

    // =========================
    // GET TASKS
    // =========================
    const tasks = await Task.find({
      meetingId: id,
    });

    // =========================
    // CREATE PDF
    // =========================
    const doc = new PDFDocument();

    // RESPONSE HEADERS
    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=meeting-report.pdf`
    );

    doc.pipe(res);

    // =========================
    // TITLE
    // =========================
    doc
      .fontSize(24)
      .text("AI Meeting Report", {
        align: "center",
      });

    doc.moveDown();

    // =========================
    // MEETING INFO
    // =========================
    doc.fontSize(18).text("Meeting Details");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(`Title: ${meeting.title}`);

    doc.text(`Status: ${meeting.status}`);

    doc.text(
      `Created: ${new Date(
        meeting.createdAt
      ).toLocaleString()}`
    );

    doc.moveDown();

    // =========================
    // TRANSCRIPT SECTION
    // =========================
    doc.fontSize(18).text("Transcript");

    doc.moveDown(0.5);

    if (meeting.transcript.length === 0) {
      doc.fontSize(12).text("No transcript.");
    } else {
      meeting.transcript.forEach((item) => {
        doc
          .fontSize(12)
          .text(
            `${item.sender}: ${item.text}`
          );
      });
    }

    doc.moveDown();

    // =========================
    // TASKS SECTION
    // =========================
    doc.fontSize(18).text("AI Action Items");

    doc.moveDown(0.5);

    if (tasks.length === 0) {
      doc.fontSize(12).text("No tasks.");
    } else {
      tasks.forEach((task, index) => {
        doc.fontSize(12).text(
          `${index + 1}. ${task.task}
Assigned To: ${task.assignedTo}
Due Date: ${task.dueDate}
Status: ${task.status}
          `
        );

        doc.moveDown(0.5);
      });
    }

    // =========================
    // FOOTER
    // =========================
    doc.moveDown();

    doc
      .fontSize(10)
      .text(
        "Generated by AI Meeting Assistant",
        {
          align: "center",
        }
      );

    // FINISH PDF
    doc.end();
  } catch (err) {
    res.status(500).json({
      message: err.message,
    });
  }
};
